- name: Docs
  tocHref: /
  topicHref: /
  items:
  - name: Visual Studio
    tocHref: /visualstudio/
    topicHref: /visualstudio/
    items:
    - name: Visual Studio Tools for Docker
      tocHref: /visualstudio/docker
      topicHref: /visualstudio/docker/
      